from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from io import BytesIO

DARK_BG = RGBColor(0x0a, 0x0a, 0x0f)
PURPLE = RGBColor(0x7c, 0x6a, 0xf7)
WHITE = RGBColor(0xff, 0xff, 0xff)
GRAY = RGBColor(0xc0, 0xc0, 0xd0)


def add_slide(prs):
    slide_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(slide_layout)
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = DARK_BG
    for shape in list(slide.shapes):
        shape.element.getparent().remove(shape.element)
    return slide


def add_text_box(slide, text, left, top, width, height, font_size=18, bold=False, color=WHITE, align=PP_ALIGN.LEFT):
    txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = str(text)
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = color


def add_accent_bar(slide):
    bar = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.08))
    bar.fill.solid()
    bar.fill.fore_color.rgb = PURPLE
    bar.line.fill.background()


def generate_pptx(analysis):
    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    idea = analysis.idea

    # Slide 1 — Title
    s = add_slide(prs)
    add_accent_bar(s)
    add_text_box(s, str(idea.title), 1, 1.5, 11, 1.5, font_size=40, bold=True, color=WHITE, align=PP_ALIGN.CENTER)
    add_text_box(s, f"{analysis.overall_score}/10 — {analysis.verdict}", 1, 3.2, 11, 0.8, font_size=28, bold=True, color=PURPLE, align=PP_ALIGN.CENTER)
    add_text_box(s, f"{idea.sector} | {idea.business_model}", 1, 4.2, 11, 0.5, font_size=16, color=GRAY, align=PP_ALIGN.CENTER)
    add_text_box(s, "Generated by PitchIQ", 1, 6.5, 11, 0.5, font_size=12, color=GRAY, align=PP_ALIGN.CENTER)

    # Slide 2 — Problem / Personas
    s = add_slide(prs)
    add_accent_bar(s)
    add_text_box(s, "The Problem", 0.5, 0.3, 12, 0.6, font_size=28, bold=True, color=PURPLE)
    for i, persona in enumerate((analysis.personas or [])[:2]):
        y = 1.2 + (i * 2.2)
        add_text_box(s, f"{persona.name}, {persona.age} — {persona.role}", 0.5, y, 12, 0.5, font_size=18, bold=True, color=WHITE)
        add_text_box(s, f"Pain point: {persona.pain_point}", 0.5, y + 0.5, 12, 0.8, font_size=14, color=GRAY)
        add_text_box(s, f"Willingness to pay: {persona.willingness_to_pay}", 0.5, y + 1.2, 12, 0.5, font_size=14, color=PURPLE)

    # Slide 3 — Solution
    s = add_slide(prs)
    add_accent_bar(s)
    add_text_box(s, "The Solution", 0.5, 0.3, 12, 0.6, font_size=28, bold=True, color=PURPLE)
    add_text_box(s, str(idea.pitch_text), 0.5, 1.2, 12, 5, font_size=16, color=WHITE)

    # Slide 4 — Viability scores
    s = add_slide(prs)
    add_accent_bar(s)
    add_text_box(s, "Viability Scores", 0.5, 0.3, 12, 0.6, font_size=28, bold=True, color=PURPLE)
    for i, score in enumerate((analysis.scores or [])[:6]):
        x = 0.5 if i < 3 else 6.8
        y = 1.2 + ((i % 3) * 1.8)
        add_text_box(s, score.dimension.replace('_', ' ').title(), x, y, 6, 0.4, font_size=14, bold=True, color=WHITE)
        add_text_box(s, f"{score.score}/10", x, y + 0.4, 6, 0.4, font_size=20, bold=True, color=PURPLE)
        add_text_box(s, str(score.justification or '')[:80], x, y + 0.8, 6, 0.7, font_size=10, color=GRAY)

    # Slide 5 — SWOT
    s = add_slide(prs)
    add_accent_bar(s)
    add_text_box(s, "SWOT Analysis", 0.5, 0.3, 12, 0.6, font_size=28, bold=True, color=PURPLE)
    swot = analysis.swot
    if swot:
        quadrants = [
            ("Strengths", swot.strengths or [], 0.5, 1.2, RGBColor(0x1d, 0x9e, 0x75)),
            ("Weaknesses", swot.weaknesses or [], 6.8, 1.2, RGBColor(0xe2, 0x4b, 0x4a)),
            ("Opportunities", swot.opportunities or [], 0.5, 4.0, RGBColor(0x37, 0x8a, 0xdd)),
            ("Threats", swot.threats or [], 6.8, 4.0, RGBColor(0xef, 0x9f, 0x27)),
        ]
        for title, items, x, y, color in quadrants:
            add_text_box(s, title, x, y, 6, 0.4, font_size=14, bold=True, color=color)
            add_text_box(s, '\n'.join([f'• {item}' for item in items[:3]]), x, y + 0.4, 6, 1.5, font_size=11, color=GRAY)

    # Slide 6 — Competitors
    s = add_slide(prs)
    add_accent_bar(s)
    add_text_box(s, "Competitor Landscape", 0.5, 0.3, 12, 0.6, font_size=28, bold=True, color=PURPLE)
    for i, comp in enumerate((analysis.competitors or [])[:4]):
        y = 1.2 + (i * 1.4)
        add_text_box(s, str(comp.name), 0.5, y, 3, 0.4, font_size=14, bold=True, color=WHITE)
        add_text_box(s, f"{comp.type.title()} | {comp.scope.title()}", 3.5, y, 3, 0.4, font_size=12, color=PURPLE)
        add_text_box(s, str(comp.hottest_product or '')[:60], 0.5, y + 0.4, 9, 0.5, font_size=11, color=GRAY)

    # Slide 7 — Pivot suggestions
    s = add_slide(prs)
    add_accent_bar(s)
    add_text_box(s, "Pivot Suggestions", 0.5, 0.3, 12, 0.6, font_size=28, bold=True, color=PURPLE)
    for i, pivot in enumerate((analysis.pivot_suggestions or [])[:2]):
        y = 1.5 + (i * 2.5)
        add_text_box(s, f"Option {i + 1}", 0.5, y, 12, 0.4, font_size=14, bold=True, color=PURPLE)
        add_text_box(s, str(pivot), 0.5, y + 0.4, 12, 1.8, font_size=14, color=WHITE)

    # Slide 8 — Next steps
    s = add_slide(prs)
    add_accent_bar(s)
    add_text_box(s, "Next Steps", 0.5, 0.3, 12, 0.6, font_size=28, bold=True, color=PURPLE)
    next_steps = [
        "1. Validate the idea with 10 potential users this week",
        "2. Build a simple landing page to test demand",
        "3. Define your MVP — the smallest version that solves the core pain",
        "4. Identify your first 3 paying customers",
        "5. Apply to a startup accelerator or university fund",
    ]
    for i, step in enumerate(next_steps):
        add_text_box(s, step, 0.5, 1.3 + (i * 1.0), 12, 0.7, font_size=15, color=WHITE)

    buffer = BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer
